### ISSUE TITLE
Gmarker is not pulling in correct latitude and longitude

### ISSUE THREAD

**Issue by CartierBailey** [craftsmancoding/gmarker#12]
I followed the instructions in installing, and created the TVs for latitude and longitude.

I did an output test to see why my map locations were way off from the actual address entered, and noticed that no matter what address I entered, the latitude and longitude values remained the same. It would not update to a new latitude and longitude.

**Comment by fireproofsocks** [comment]
Closing this... v2 has massive rewrites including greater transparency for testing.
