### ISSUE TITLE
Google api v3 doesn't require API keys no more.

### ISSUE THREAD

**Issue by remort** [craftsmancoding/gmarker#17]
Google api v3 doesn't require API keys no more. Should i still get a key to work with your plugin.
I need a pass long and latt from a corresponding TVs to a snippet to draw a map with a marker in center of these coords for every page in MODX. Do i need a google api key for that?

**Comment by fireproofsocks** [comment]
Although the Google Maps API doesn't *require* an API key, it is strongly recommended: otherwise API lookups get tracked against an IP address, so this can mean that the quota is quickly exhausted when using it on a shared server.
