### ISSUE TITLE
Standart marker template doesn't work

### ISSUE THREAD

**Issue by remort** [craftsmancoding/gmarker#18]
It just don't get coordinates for declaring a variable. I changed it and created fixed version of a chunk. Look at the first string for the changes. Chunk code is here:

```
var markerLatlng[[+idx]] = new google.maps.LatLng([[*coords]]);
var marker[[+idx]] = new google.maps.Marker({
        "position": markerLatlng[[+idx]],
        "map": myMap,
        "draggable":false,
        "title":"[[+pagetitle]]",
        [[+drop]]
        "icon": 'https://chart.googleapis.com/chart?chst=d_map_pin_letter&chld=[[+marker_center]]|[[+marker_color]]|000000',
        [[+shadow]]
});
[[+info]]
marker[[+idx]].mycategory = [[+group_json]];
this.gmarkers.push(marker[[+idx]]);
marker[[+idx]].setVisible(true);
```

var markerLatlng[[+idx]] gets empty ("") with default chunkcode.

And that is my snippet call.
```
[[Gmarker? &latlng=`[[*coords]]` &templates=`2` &zoom=`14` &markerTpl=`coordsMarker` ]]
```

And that is my typical coords TV content:
'36.546691,32.011562'

May be it works wrong because i centered my logic on getting certain map coords from an already filled up TV parameter.
Modx  2.2.10-pl.

**Comment by fireproofsocks** [comment]
v2 has completely refactored this.  It includes an example map.
