### ISSUE TITLE
gmarker snippet creates 75 (!) markers. page loading hangs on a moment before done.

### ISSUE THREAD

**Issue by remort** [craftsmancoding/gmarker#19]
My snippet call:
[code]
[[Gmarker? &latlng=`[[*coords]]` &zoom=`14` &markerTpl=`coordsMarker`]]
[code]

My page JS code block is huge and contains 75 blocks like following piece:
[code]
			var markerLatlng1 = new google.maps.LatLng(36.546691,32.011562);

var marker1 = new google.maps.Marker({
        "position": markerLatlng1,
        "map": myMap,
        "draggable":false,
        "title":"1st new",
         icon:'http://www.google.com/intl/en_us/mapfiles/ms/micons/red-dot.png',
});

		var contentString1 = "<h2><a href=\"news\/1st-new.html\">1st new<\/a><\/h2>";
		google.maps.event.addListener(marker1, 'click', function() { 
			infowindow.close();
			infowindow.setContent(contentString1);
			infowindow.open(myMap,marker1); 
		});
[code]

Just number of var markerLatlng1 - 75 is changing.

I found this strange logic in snippet code. The foreach loop creates this markers. What for?
I need only one marker on map, that points to given coordinates.

So in the very end of iteration code , after "$letter++;" string i aded a "break;" operator to run foreach cycle only once a time.

Now it works fine. Page loads fast. But what it was made for? Just an ugly surprice.

PS: And guys. your website is lagging, shows loads of php errors.

**Comment by fireproofsocks** [comment]
v2 has completely refactored this and how it works. Look for the new version.
