### ISSUE TITLE
Change from Pixel width to Percentage

### ISSUE THREAD

**Issue by jwmsales** [craftsmancoding/gmarker#21]
It would be nice to switch from pixels to percentage widths for the map. It would make it easier to use on multiple devices.

**Comment by fireproofsocks** [comment]
Thanks Jack!  Working on integrating this for a project.  Did you add NEW TVs for the percentage based dimensions?  Or did you just re-purpose the existing TVs?  Can you paste a sample of the relevant chunks here?  I'd like to feature your example on the project wiki if that's all right.

**Comment by jwmsales** [comment]
Everett

I made a couple of changes to the code that were significant. First, it wasn't working on IE9 and I found a stray comma somewhere (trying to find the file and send it).

Second, I used custom icons for the map markers. The change I made was to upload to my server a group of icons that are custom and then had to use a complete path call to get them. You will notice in the path a TV "resourceType" that is used a lot throughout the site. This was how I named the icons. This is how I changed your code:

var markerLatlng[[+idx]] = new google.maps.LatLng([[+[[++gmarker.lat_tv]]]],[[+[[++gmarker.lng_tv]]]]);
var marker[[+idx]] = new google.maps.Marker({
	"position" : markerLatlng[[+idx]],
	"map" : myMap,
	"draggable" : false,
	"title" : "[[+pagetitle]]",
	[[+drop]]
	[[+shadow]]
	"icon" : "http://devresources.healthshack.info/img/[[+resourceType]].png"
});

[[+info]]
marker[[+idx]].mycategory = [[+group_json]]; 
this.gmarkers.push(marker[[+idx]]);
marker[[+idx]].setVisible(true);

//
This is the call I made in my page template to get the map:

[[Gmarker? &address=`[[*resourceCity]], [[*resourceState]]` &height=`300` &width=`100` &zoom=`11` &parents=`[[*docID]]` ]]

//
To make the map 100% and responsive I changed the gmapshead chunk to this (width is a percentage instead of PX):

<script type="text/javascript" src="[[+gmarker_url]]"></script>

<script type="text/javascript">
	/**
	 * Used by the Gmarker Extra
	 */

	function gmarkers_init() {

		// Lat/Lng of map center
		var myLatlng = new google.maps.LatLng([[+lat]],[[+lng]]);
		
		var mapOptions = {
			"zoom": [[+zoom]],
			"center": myLatlng,
			"mapTypeId": google.maps.MapTypeId.[[+type]]
		}
		
		// Draw my map
		var myMap = new google.maps.Map(document.getElementById("[[+id]]"), mapOptions);	
	}
		
	window.onload = gmarkers_init;
</script>

<style>
	#[[+id]] {
		height:[[+h]]px;
		width: [[+w]]%;
		background:#A9A9A9;
	}
</style>

That should be it. If needed I can grab all of the files and email them to you.

Jack McDaniel | Creative Director
720.495.1368 | impress-design.com <http://impress-design.com/>
 <http://impress-design.com/>

**Comment by jwmsales** [comment]
For Repoman, did you get the github login and figure anything out. Resources are being packaged up but they won't install with the package.

Jack McDaniel | Creative Director
720.495.1368 | impress-design.com <http://impress-design.com/>
 <http://impress-design.com/>

**Comment by fireproofsocks** [comment]
Perhaps the better solution for height and width is to let user specify % or px, e.g. `height:[[+h]];` where the value could be `500px` or `80%` etc.

I wonder where that stray comma was... I'm trying to re-do the organization of the JS to make it simpler b/c the persistent problem with this Snippet was that the JS that it generated was prone to glitches.  Instead I'm trying to leverage straight up JSON output so it can be used in an Ajax call.

I haven't dug into the Repoman thing yet: if you want, you can add a ticket on that project to help keep issues/conversations organized.

**Comment by jwmsales** [comment]
A ticket would be good. Ted is busy but wants to get the output right. Everything is getting packaged up nicely and he says he really likes using it.

Jack McDaniel | Creative Director
720.495.1368 | impress-design.com <http://impress-design.com/>
 <http://impress-design.com/>

**Comment by jwmsales** [comment]
It would be good to have a dashboard that lets the user enter certain parameters like the height and width. That would make it real easy to use. BTW, I use the hidden TVs for the location info.

Jack McDaniel | Creative Director
720.495.1368 | impress-design.com <http://impress-design.com/>
 <http://impress-design.com/>

**Comment by fireproofsocks** [comment]
This has been implemented in the latest version.  Will be released as v2.
