### ISSUE TITLE
Can't get simple map to work

### ISSUE THREAD

**Issue by greyskymedia** [craftsmancoding/gmarker#7]
THANKS FOR THE PLUGIN!!

I just can't seem to get it to work.

There are no errors in the log, it's just simply not rendering anything.

My call is:
```
[[Gmap? &address=`11375 Sunrise Park Drive, Suite 500, Rancho Cordova, CA 95742`]]
```

Any thoughts?

**Comment by fireproofsocks** [comment]
Closing this.  We're releasing v2 soon with updated docs etc.
