### ISSUE TITLE
Glocation fill with TV

### ISSUE THREAD

**Issue by Coobi** [craftsmancoding/gmarker#8]
Hello,

I have a question about the Snippet "glocation" i would fill the Snippet call with TV like this:

[[!glocation? &adress='[[*street]], [[*city]], [[*state]]

Bit the snippet doesn't work with TV Variables.

Can you help me ?

Thanks

Coobi

**Comment by fireproofsocks** [comment]
Closing this.  v2 has completely refactored all the logic (and snippets) involved.
